#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Set-Object
version:      1.04
version_from: Object.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
